# Generated by Django 5.2.10 on 2026-01-20 06:11

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
