# Generated by Django 5.2.10 on 2026-01-21 03:59

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_ai_feedback_resume_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
