# Generated by Django 5.2.10 on 2026-02-12 03:54
from django.db import migrations, models
import json

def backfill_ai_feedback(apps, schema_editor):
    Resume = apps.get_model("resumes", "Resume")
    for r in Resume.objects.all():
        try:
            json.loads(r.ai_feedback)
        except Exception:
            r.ai_feedback = json.dumps({"status": r.ai_feedback or "", "skills": [], "matches": []})
            r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_alter_resume_embedding'),
    ]
    
    operations = [
        migrations.RunPython(backfill_ai_feedback),
        migrations.AlterField(
            model_name='resume',
            name='ai_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]