# Generated by Django 5.2.10 on 2026-01-21 05:05

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_at_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
